import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from '@/components/SideBar/sideBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col'>
          <div className='fixed z-20 w-screen  '>
            <SideBar></SideBar>
          </div>
          <div className='mt-[62px]'>
            {children}
          </div>
        </div>
        </body>
    </html>
  )
}
